# Scratch

A notebook for exploring Python, Jupyter, etc.

In [1]:
D = 100
d = 50

In [2]:
D

100

In [3]:
d

50

In [4]:
whos

Variable   Type    Data/Info
----------------------------
D          int     100
d          int     50


In [5]:
import numpy as np

In [21]:
Lx = 8
dx = 0.5
x = np.arange(start=0, stop=Lx, step=dx)
nx = len(x)

In [22]:
nx

16

In [23]:
x

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5])

In [24]:
x1 = np.linspace(start=0, stop=Lx, num=int(Lx/dx), endpoint=True) 

In [25]:
x1

array([0.        , 0.53333333, 1.06666667, 1.6       , 2.13333333,
       2.66666667, 3.2       , 3.73333333, 4.26666667, 4.8       ,
       5.33333333, 5.86666667, 6.4       , 6.93333333, 7.46666667,
       8.        ])

In [26]:
C = np.zeros_like(x)
C_left = 500
C_right = 0
C[x <=Lx//2] = C_left
C[x > Lx//2] = C_right

In [27]:
C

array([500., 500., 500., 500., 500., 500., 500., 500., 500.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.])

In [28]:
C[-1]

np.float64(0.0)

In [29]:
x[-1]

np.float64(7.5)